// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const isSupabaseMigrate = process.env.PRISMA_USE_DIRECT_URL === "1";

console.log(`DEPLOYING TO ${isSupabaseMigrate ? "DIRECT_URL" : "DATABASE_URL"}`);

const databaseUrl = isSupabaseMigrate
  ? process.env.DIRECT_URL ?? process.env.DATABASE_URL
  : process.env.DATABASE_URL ?? process.env.DIRECT_URL;

if (!databaseUrl) {
  throw new Error("DATABASE_URL or DIRECT_URL must be set");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
